# permissions for end users to view falcon-sensors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falcon-sensor-viewer-role
rules:
- apiGroups:
  - crowdstrike.com
  resources:
  - falcon-sensors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crowdstrike.com
  resources:
  - falcon-sensors/status
  verbs:
  - get
