# permissions for end users to view falconsensors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falconsensor-viewer-role
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconsensors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconsensors/status
  verbs:
  - get
