# permissions for end users to edit falcon-sensors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falcon-sensor-editor-role
rules:
- apiGroups:
  - crowdstrike.com
  resources:
  - falcon-sensors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crowdstrike.com
  resources:
  - falcon-sensors/status
  verbs:
  - get
