# permissions for end users to edit falconsensors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falconsensor-editor-role
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconsensors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconsensors/status
  verbs:
  - get
