apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

# We need to manage Helm release daemonsets
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - daemonset
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# We need to access the coreos nodes to protect them
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - "*"

# We need to easily pull images regardless of namespace
- apiGroups:
  - ""
  - image.openshift.io
  resources:
  - imagestreamimages
  - imagestreammappings
  - imagestreams
  - imagestreamtags
  - imagetags
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - image.openshift.io
  resources:
  - imagestreams/layers
  verbs:
  - get

##
## Rules for falcon.crowdstrike.com/v1alpha1, Kind: FalconSensor
##
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconsensors
  - falconsensors/status
  - falconsensors/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "serviceaccounts"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "daemonsets"

#+kubebuilder:scaffold:rules
