apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconSensor
metadata:
  name: falcon-helm
spec:
  # Default values copied from <project_dir>/helm-charts/falcon-sensor/values.yaml
  container:
    certExpiration: 3650
    disableNSInjection: false
    disablePodInjection: false
    enabled: false
    image:
      pullPolicy: Always
      pullSecrets:
        enable: false
        namespaces: null
        registryConfigJSON: null
      repository: falcon-sensor
      tag: latest
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
  falcon:
    aid: null
    apd: null
    aph: null
    app: null
    assert: null
    billing: null
    cid: null
    feature: null
    memfail_every_n: null
    memfail_grace_period: null
    message_log: null
    provisioning_token: null
    tags: null
    trace: null
    update: null
  node:
    daemonset:
      annotations: {}
      labels: {}
      tolerations: []
      updateStrategy: RollingUpdate
    enabled: true
    fullnameOverride: ""
    image:
      pullPolicy: Always
      pullSecrets: {}
      repository: falcon-node-sensor
      tag: latest
    nameOverride: ""
    podAnnotations: {}
    terminationGracePeriod: 10
