apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ include "falcon-sensor.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  {{- range $key, $value := .Values.falcon }}
  {{- if .Values.falcon.$value }}
  FALCONCTL_OPT_{{ $key | upper }}: {{ .Values.falcon.$value | quote }}
  {{- end }}
  {{- end }}

  #  FALCONCTL_OPT_CID: {{ .Values.falcon.cid | quote }}
  #FALCONCTL_OPT_AID: {{ .Values.falcon.aid | quote }}
  #FALCONCTL_OPT_APD: {{ .Values.falcon.apd | quote }}
  #FALCONCTL_OPT_APH: {{ .Values.falcon.aph | quote }}
  #FALCONCTL_OPT_APP: {{ .Values.falcon.app | quote }}
  #FALCONCTL_OPT_TRACE: {{ .Values.falcon.trace | quote }}
  #FALCONCTL_OPT_FEATURE: {{ .Values.falcon.feature | quote }}
  #FALCONCTL_OPT_MESSAGE_LOG: {{ .Values.falcon.message_log | quote }}
  #FALCONCTL_OPT_BILLING: {{ .Values.falcon.billing | quote }}
  #FALCONCTL_OPT_ASSERT: {{ .Values.falcon.assert }}
  #FALCONCTL_OPT_MEMFAIL_GRACE_PERIOD: {{ .Values.falcon.memfail_grace_period | quote }}
  #FALCONCTL_OPT_MEMFAIL_EVERY_N: {{ .Values.falcon.memfail_every_n | quote }}
