apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ include "falcon-sensor.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}

data:
  FALCONCTL_OPT_CID: {{ .values.FALCONCTL_OPT_CID | quote }}
  FALCONCTL_OPT_AID: {{ .values.FALCONCTL_OPT_AID | quote }}
  FALCONCTL_OPT_APD: {{ .values.FALCONCTL_OPT_APD | quote }}
  FALCONCTL_OPT_APH: {{ .values.FALCONCTL_OPT_APH | quote }}
  FALCONCTL_OPT_APP: {{ .values.FALCONCTL_OPT_APP | quote }}
  FALCONCTL_OPT_TRACE: {{ .values.FALCONCTL_OPT_TRACE | quote }}
  FALCONCTL_OPT_FEATURE: {{ .values.FALCONCTL_OPT_FEATURE | quote }}
  FALCONCTL_OPT_MESSAGE_LOG: {{ .values.FALCONCTL_OPT_MESSAGE_LOG | quote }}
  FALCONCTL_OPT_BILLING: {{ .values.FALCONCTL_OPT_BILLING | quote }}
  FALCONCTL_OPT_ASSERT: {{ .values.FALCONCTL_OPT_ASSERT }}
  FALCONCTL_OPT_MEMFAIL_GRACE_PERIOD: {{ .values.FALCONCTL_OPT_MEMFAIL_GRACE_PERIOD | quote }}
  FALCONCTL_OPT_MEMFAIL_EVERY_N: {{ .values.FALCONCTL_OPT_MEMFAIL_EVERY_N | quote }}
