apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ include "falcon-sensor.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  FALCONCTL_OPT_CID: {{ .Values.falcon.cid }}
  {{- range $key, $value := .Values.falcon }}
  {{- if and ($value) (ne $key "cid") }}
  FALCONCTL_OPT_{{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.container.enabled }}
  CP_NAMESPACE: {{ .Release.Namespace }}
  FALCON_IMAGE_PULL_POLICY: "{{ .Values.container.image.pullPolicy }}"
  FALCON_IMAGE: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}"
  {{- if .Values.container.image.pullSecrets.enable }}
  FALCON_IMAGE_PULL_SECRET: crowdstrike-falcon-pull-secret
  {{- end }}
  {{- if .Values.container.disablePodInjection }}
  INJECTION_DEFAULT_DISABLED: T
  {{- end }}
  {{- end }}
