{{- if .Values.container.enabled }}
{{- if .Values.container.image.pullSecrets.enable }}
{{- $registry := .Values.container.image.pullSecrets.registryConfigJSON }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-pull-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ $registry }}
type: kubernetes.io/dockerconfigjson
{{- if .Values.container.image.pullSecrets.namespaces }}
{{- $name := (printf "%s-pull-secret" (include "falcon-sensor.fullname" .)) }}
{{- $myns := list -}}
{{- if .Values.container.image.pullSecrets.allNamespaces }}
{{- range $index, $ns := (lookup "v1" "Namespace" "" "").items -}}
  {{ $myns = append $myns $ns.metadata.name }}
{{- end }}
{{- else -}}
{{- $myns := split "," .Values.container.image.pullSecrets.namespaces -}}
{{- end }}
{{- range $value := $myns }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $value }}
data:
  .dockerconfigjson: {{ $registry }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
{{- end }}
{{- end }}
