{{- if .Values.container.enabled }}
{{- if .Values.container.image.pullSecrets.enable }}
{{- $registry := .Values.container.image.pullSecrets.registryConfigJSON }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-pull-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ $registry }}
type: kubernetes.io/dockerconfigjson
{{- if .Values.container.image.pullSecrets.namespaces }}
---
{{- range $value := split "," .Values.container.image.pullSecrets.namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-pull-secret
  namespace: {{ $value }}
data:
  .dockerconfigjson: {{ $registry }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
{{- end }}
{{- end }}