{{- if .Values.container.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-access-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "falcon-sensor.fullname" . }}-access-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}