{{- if .Values.container.enabled }}
{{- if .Values.container.image.pullSecrets.enable }}
{{- $registry := .Values.container.image.pullSecrets.registryConfigJSON }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-pull-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ $registry }}
type: kubernetes.io/dockerconfigjson
{{- if .Values.container.image.pullSecrets.namespaces }}
{{- $name := (printf "%s-pull-secret" (include "falcon-sensor.fullname" .)) }}
{{- range $value := split "," .Values.container.image.pullSecrets.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $value }}
data:
  .dockerconfigjson: {{ $registry }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
{{- end }}
{{- end }}
