{{- if .Values.container.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: falcon-injector
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: falcon-injector
  ports:
    - port: 443
      targetPort: api
{{- end }}
