apiVersion: v1
kind: ServiceAccount
metadata:
  name: crowdstrike-falcon-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "falcon-sensor.name" . }}
    app.kubernetes.io/name: {{ include "falcon-sensor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "all_sensors"
    helm.sh/chart: {{ include "falcon-sensor.chart" . }}