{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "falcon-image-analyzer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "falcon-image-analyzer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
    {{- include "falcon-image-analyzer.labels" . | nindent 8 }}
    spec:
      {{- if .Values.crowdstrikeConfig.dockerAPIToken }}
      imagePullSecrets:
        - name: {{ include "falcon-image-analyzer.fullname" . }}-pull-secret
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name | default ( include "falcon-image-analyzer.fullname" . ) }}
      securityContext:
      {{- if .Values.podSecurityContext }}
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- if .Values.securityContext }}
          {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          resources:
          {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          image: {{ include "falcon-image-analyzer.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-runmode", "watcher"]
          envFrom:
            - configMapRef:
                name: {{ include "falcon-image-analyzer.fullname" . }}
            - secretRef:
                {{- if .Values.crowdstrikeConfig.existingSecret }}
                name: {{ .Values.crowdstrikeConfig.existingSecret }}
                {{- else }}
                name: {{ include "falcon-image-analyzer.fullname" . }}
                {{- end }}
          volumeMounts:
           {{- toYaml .Values.volumeMounts | default "" | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | default "" | nindent 8 }}
      {{- end}}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.crowdstrikeConfig.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
{{- end }}
