{{ if .Values.crowdstrikeConfig.dockerAPIToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-image-analyzer.fullname" . }}-regsecret
  labels:
  {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
  {{- end}}
  