# Default values for falcon-sensor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

daemonset:
  # Annotations to apply to the daemonset
  annotations: {}

  # additionals labels
  labels: {}

  updateStrategy: RollingUpdate

  # Various pod security context settings. Bear in mind that many of these have an impact
  # on the Falcon Sensor working correctly.
  #
  # - User that the container will execute as. Typically necessary to run as root (0).
  # - Runs the Falcon Sensor containers as privileged containers. Typically not
  #   necessarily unless running within environments such as OpenShift.
  securityContext:
    runAsUser: 0
    privileged: false

image:
  repository: falcon-sensor
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# Override various naming aspects of this chart
# Only edit these if you know what you're doing
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

namespace: default

# How long to wait for Filebeat pods to stop gracefully
terminationGracePeriod: 30

falcon:
  cid:
  aid:
  apd:
  aph:
  app:
  trace:
  feature:
  message_log:
  billing:
  assert:
  memfail_grace_period:
  memfail_every_n:
  provisioning_token:
