# Default values for falcon-sensor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

node:
  # When enabled, Helm chart deploys the Falcon Senors to Kubernetes nodes
  enabled: true

  daemonset:
    # Annotations to apply to the daemonset
    annotations: {}

    # additionals labels
    labels: {}

    updateStrategy: RollingUpdate

    # Various pod security context settings. Bear in mind that many of these have an impact
    # on the Falcon Sensor working correctly.
    #
    # - User that the container will execute as. Typically necessary to run as root (0).
    # - Runs the Falcon Sensor containers as privileged containers. This is required when
    #   running the Falcon Linux Sensor on Kubernetes nodes to properly run in the node's
    #   kernel and to actually protect the node..
    securityContext:
      runAsUser: 0
      privileged: true
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: true

  image:
    repository: falcon-node-sensor
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  # Override various naming aspects of this chart
  # Only edit these if you know what you're doing
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  namespace: default

  # How long to wait for Falcon pods to stop gracefully
  terminationGracePeriod: 10

falcon:
  cid:
  aid:
  apd:
  aph:
  app:
  trace:
  feature:
  update:
  message_log:
  billing:
  assert:
  memfail_grace_period:
  memfail_every_n:
  provisioning_token:
