# Default values for falcon-image-analyzer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

daemonset:
  enabled: false

deployment:
  enabled: false

replicaCount: 1
image:
  repository: eng-cloud-docker-sandbox-local.artifactory.crwd.dev/cloud/cs-imageanalyzer
  # Overrides the image tag. In general, tags should not be used (including semver tags or `latest`). This variable is provided for those
  # who have yet to move off of using tags. The sha256 digest should be used in place of tags for increased security and image immutability.
  tag:
  # Setting a digest will override any tag and should be used instead of tags.
  #
  # Example digest variable configuration:
  # digest: sha256:ffdc91f66ef8570bd7612cf19145563a787f552656f5eec43cd80ef9caca0398
  digest:
  pullPolicy: IfNotPresent
  envFrom:
    - configMapRef:
        name: agent-config

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Annotations to add to the service account
  name: ""
  annotations: {}

volumeMounts:
  - mountPath: /tmp
    name: tmp-volume

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

resources: {}

tolerations: []

affinity: {}

priorityClassName: ""

# This is a mandatory mount for both deployment and daemon set.
# this is used as a tmp working space for image storage
volumes:
  - name: tmp-volume
    emptyDir:
      sizeLimit: 20Gi

crowdstrikeConfig:
  clusterName: ""
  enableDebug: "false"
  clientID: ""
  clientSecret: ""
  cid: ""
  dockerAPIToken: ""
  existingSecret: ""
  agentRunmode: "watcher"
  agentRegion: "us-1"
  agentRuntime: ""
  agentRuntimeSocket: ""
  agentMaxConsumerThreads: "1"
