apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cs-k8s-protection-agent.fullname" . }}
  labels:
  {{- include "cs-k8s-protection-agent.labels" . | nindent 4 }}
data:
  AGENT_CLUSTER_NAME: {{ .Values.crowdstrikeConfig.clusterName | quote }}
  AGENT_DEBUG: {{ .Values.crowdstrikeConfig.enableDebug | default "false" | quote }}
  AGENT_ENV: {{ .Values.crowdstrikeConfig.env | quote }}
  AGENT_HELM_VERSION: {{ .Chart.Version | quote }}
  HTTP_PROXY: {{ .Values.proxyConfig.HTTP_PROXY | default "" }}
  HTTPS_PROXY: {{ .Values.proxyConfig.HTTPS_PROXY | default "" }}
  NO_PROXY: {{ .Values.proxyConfig.NO_PROXY | default "" }}

